services:
  eps.vhost_generator.apache.vhost_node_factory:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Node\Factory\ApacheVHostNodeFactory
    arguments:
      - @eps.vhost_generator.apache.directory_node_factory

  eps.vhost_generator.apache.directory_node_factory:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Node\Factory\DirectoryNodeFactory

  eps.vhost_generator.apache.formatter:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Formatter\ApacheVHostFormatter

  eps.vhost_generator.apache.generator:
    class: Eps\VhostGeneratorBundle\Generator\Apache\ApacheGenerator
    arguments:
      - @eps.vhost_generator.apache.vhost_node_factory
      - @eps.vhost_generator.apache.formatter
