services:
  vhost_generator.apache.command.generate:
    class: Eps\VhostGeneratorBundle\Command\GenerateVHostCommand
    calls:
      - [setInstaller, [@vhost_generator.installer.apache]]
    tags:
      - { name: console.command }
