services:
  # Generic
  eps.vhost_generator.installer.apache.factory:
    class: Eps\VhostGeneratorBundle\Installer\Apache\ApacheInstallerFactory
    arguments:
      - @eps.vhost_generator.os_detector
    tags:
      - { name: vhost_installer_factory, server: apache }

  eps.vhost_generator.installer.apache:
    class: Eps\VhostGeneratorBundle\Installer\InstallerInterface
    factory: [@eps.vhost_generator.installer.apache.factory, 'getInstaller']

  # Installers
  eps.vhost_generator.installer.apache.linux:
    class: Eps\VhostGeneratorBundle\Installer\Apache\LinuxInstaller
    arguments:
      - @filesystem
      - @eps.vhost_generator.process_factory
    calls:
      - [setGenerator, [@eps.vhost_generator.apache.generator]]
      - [setVHosts, [%eps.vhost_generator.apache.vhosts%]]
      - [setVHostsPath, [%eps.vhost_generator.apache.vhosts_path%]]
      - [setOutputFile, [%eps.vhost_generator.apache.output_file%]]
    tags:
      - { name: vhost_installer.apache, os: linux }
