services:
  vhost_generator.apache.vhost_node_factory:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Node\Factory\ApacheVHostNodeFactory
    arguments:
      - @vhost_generator.apache.directory_node_factory

  vhost_generator.apache.directory_node_factory:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Node\Factory\DirectoryNodeFactory

  vhost_generator.apache.generator:
    class: Eps\VhostGeneratorBundle\Generator\Apache\ApacheGenerator
    arguments:
      - @vhost_generator.apache.vhost_node_factory
      - @vhost_generator.apache.formatter

  vhost_generator.apache.formatter:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Formatter\ApacheVHostFormatter

  vhost_generator.process_factory:
    class: Eps\VhostGeneratorBundle\Util\SymfonyProcessFactory

  vhost_generator.installer.apache.linux:
    class: Eps\VhostGeneratorBundle\Installer\Apache\LinuxInstaller
    arguments:
      - @filesystem
      - @vhost_generator.process_factory
    calls:
      - [setGenerator, [@vhost_generator.apache.generator]]
      - [setVHosts, [%vhost_generator.apache.vhosts%]]
      - [setVHostsPath, [%vhost_generator.apache.vhosts_path%]]
      - [setOutputFile, [%vhost_generator.apache.output_file%]]


  vhost_generator.apache.command.generate:
    class: Eps\VhostGeneratorBundle\Command\GenerateVHostCommand
    calls:
      - [setInstaller, [@vhost_generator.installer.apache.linux]]
    tags:
      - { name: console.command }
