services:
  vhost_generator.apache.vhost_node_factory:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Node\Factory\ApacheVHostNodeFactory
    arguments:
      - @vhost_generator.apache.directory_node_factory

  vhost_generator.apache.directory_node_factory:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Node\Factory\DirectoryNodeFactory

  vhost_generator.apache.generator:
    class: Eps\VhostGeneratorBundle\Generator\Apache\ApacheGenerator
    arguments:
      - @vhost_generator.apache.vhost_node_factory
      - @vhost_generator.apache.formatter

  vhost_generator.apache.formatter:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Formatter\ApacheVHostFormatter

  vhost_generator.process_factory:
    class: Eps\VhostGeneratorBundle\Util\SymfonyProcessFactory

  vhost_generator.installer.apache.factory:
    class: Eps\VhostGeneratorBundle\Installer\Apache\ApacheInstallerFactory
    arguments:
      - @vhost_generator.os_detector
    tags:
      - { name: vhost_installer_factory, server: apache }

  vhost_generator.installer.apache:
    class: Eps\VhostGeneratorBundle\Installer\InstallerInterface
    factory: [@vhost_generator.installer.apache.factory, 'getInstaller']

  vhost_generator.installer.apache.linux:
    class: Eps\VhostGeneratorBundle\Installer\Apache\LinuxInstaller
    arguments:
      - @filesystem
      - @vhost_generator.process_factory
    calls:
      - [setGenerator, [@vhost_generator.apache.generator]]
      - [setVHosts, [%vhost_generator.apache.vhosts%]]
      - [setVHostsPath, [%vhost_generator.apache.vhosts_path%]]
      - [setOutputFile, [%vhost_generator.apache.output_file%]]
    tags:
      - { name: vhost_installer.apache, os: linux }


  vhost_generator.apache.command.generate:
    class: Eps\VhostGeneratorBundle\Command\GenerateVHostCommand
    calls:
      - [setInstaller, [@vhost_generator.installer.apache]]
    tags:
      - { name: console.command }

  vhost_generator.operating_system:
    class: Eps\VhostGeneratorBundle\Util\OperatingSystem

  vhost_generator.os_detector:
    class: Eps\VhostGeneratorBundle\Util\OsDetector
    arguments:
      - @vhost_generator.operating_system
