services:
  vhost_generator.apache.vhost_node_factory:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Node\Factory\ApacheVHostNodeFactory
    arguments:
      - @vhost_generator.apache.directory_node_factory

  vhost_generator.apache.directory_node_factory:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Node\Factory\DirectoryNodeFactory

  vhost_generator.apache.generator:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Generator
    arguments:
      - @vhost_generator.apache.vhost_node_factory
      - @vhost_generator.apache.formatter

  vhost_generator.apache.formatter:
    class: Eps\VhostGeneratorBundle\Generator\Apache\Formatter\ApacheVHostFormatter

  vhost_generator.process_factory:
    class: Eps\VhostGeneratorBundle\Util\SymfonyProcessFactory

  vhost_generator.apache.command.generate:
    class: Eps\VhostGeneratorBundle\Command\GenerateVHostCommand
    calls:
      - ['setGenerator', [@vhost_generator.apache.generator]]
      - ['setFilesystem', [@filesystem]]
      - ['setProcessFactory', [@vhost_generator.process_factory]]
    tags:
      - { name: console.command }
