services:
  eps.vhost_generator.process_factory:
    class: Eps\VhostGeneratorBundle\Util\SymfonyProcessFactory

  eps.vhost_generator.operating_system:
    class: Eps\VhostGeneratorBundle\Util\OperatingSystem

  eps.vhost_generator.os_detector:
    class: Eps\VhostGeneratorBundle\Util\OsDetector
    arguments:
      - @eps.vhost_generator.operating_system
