services:
  vhost_generator.process_factory:
    class: Eps\VhostGeneratorBundle\Util\SymfonyProcessFactory

  vhost_generator.operating_system:
    class: Eps\VhostGeneratorBundle\Util\OperatingSystem

  vhost_generator.os_detector:
    class: Eps\VhostGeneratorBundle\Util\OsDetector
    arguments:
      - @vhost_generator.operating_system
